#spring.application.name=camundaElastic
#spring.elasticsearch.rest.uris=http://localhost:9200

spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm.admin-user:
  id: demo
  password: demo

spring:
  elasticsearch:
    rest:
      uris: "http://localhost:9200"